version: "3"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules

    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - nest

networks:
  nest:
