version: "3"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules

    environment:
      PORT: 3000
      MYSQL_HOST: mariadb
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_DB: nest
      MYSQL_PORT: 3306
      SECRET: sajsfvdasd6c45ad6c3cc
    ports:
      - "3000:3000"
    networks:
      - nest
    links:
      - mariadb
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - nest_dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nest
      MYSQL_USER: nest
      MYSQL_PASSWORD: nest
      MYSQL_DATABASE: nest
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_czech_ci
    networks:
      - nest

  adminer:
    image: adminer
    restart: always
    ports:
      - "4200:8080"
    environment:
      ADMINER_DESIGN: pepa-linha
    links:
      - mariadb
    depends_on:
      - mariadb
    networks:
      - nest
volumes:
  nest_dbdata:

networks:
  nest:
